# Naive Bayes Algorithm

---

### Importing Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.datasets import load_iris

<h3> GuassianNB

In [2]:
# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Gaussian Naive Bayes model
gnb = GaussianNB()

# Train the model
gnb.fit(X_train, y_train)

# Make predictions
y_pred = gnb.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Display the confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

# Display the classification report
class_report = classification_report(y_test, y_pred, target_names=iris.target_names)
print("Classification Report:\n", class_report)

Accuracy: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



<h3> MultinomialNB

In [3]:
mnb = MultinomialNB()
# Train the model

mnb.fit(X_train, y_train)

y_pred_mnb = mnb.predict(X_test)

#Evalute the model

accuracy_mnb = accuracy_score(y_test, y_pred_mnb)
print("MultinomialNB Accuracy:", accuracy_mnb)

conf_matrix_mnb = confusion_matrix(y_test, y_pred_mnb)
print("MultinomialNB Confusion Matrix:\n", conf_matrix_mnb)

class_report_mnb = classification_report(y_test, y_pred_mnb, target_names=iris.target_names)
print("MultinomialNB Classification Report:\n", class_report_mnb)

MultinomialNB Accuracy: 0.9
MultinomialNB Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  3  8]]
MultinomialNB Classification Report:
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.75      1.00      0.86         9
   virginica       1.00      0.73      0.84        11

    accuracy                           0.90        30
   macro avg       0.92      0.91      0.90        30
weighted avg       0.93      0.90      0.90        30



In [4]:
bnb = BernoulliNB()

# Train the model
bnb.fit(X_train, y_train)

# Make predictions
y_pred_bnb = bnb.predict(X_test)

# Evaluate the model
accuracy_bnb = accuracy_score(y_test, y_pred_bnb)
print("BernoulliNB Accuracy:", accuracy_bnb)

# Display the confusion matrix
conf_matrix_bnb = confusion_matrix(y_test, y_pred_bnb)
print("BernoulliNB Confusion Matrix:\n", conf_matrix_bnb)

# Display the classification report
class_report_bnb = classification_report(y_test, y_pred_bnb, target_names=iris.target_names)
print("BernoulliNB Classification Report:\n", class_report_bnb)

BernoulliNB Accuracy: 0.3
BernoulliNB Confusion Matrix:
 [[ 0 10  0]
 [ 0  9  0]
 [ 0 11  0]]
BernoulliNB Classification Report:
               precision    recall  f1-score   support

      setosa       0.00      0.00      0.00        10
  versicolor       0.30      1.00      0.46         9
   virginica       0.00      0.00      0.00        11

    accuracy                           0.30        30
   macro avg       0.10      0.33      0.15        30
weighted avg       0.09      0.30      0.14        30



c:\ProgramData\miniconda3\envs\ml_ai\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\ProgramData\miniconda3\envs\ml_ai\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\ProgramData\miniconda3\envs\ml_ai\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
